# fly.toml app configuration file generated for make-it-happen-backend on 2025-09-04T16:11:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'make-it-happen-backend'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.autoscale]
    min = 1
    max = 1

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
